In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("D:\\Projekte\\S.M.A.R.T.-Sovereign_Mail_Assessment_and_Rating_Tool\\scanner\\database\\domainlist.db")

df = pd.read_sql_query("SELECT * FROM osm_names", conn)

df

,id,osm_type,name,federal_state,website,contact_website,contact_email,wikipedia,wikidata,profil,extracted_at
0,94190766,node,Rathaus,Baden-Wuerttemberg,NaN,NaN,NaN,NaN,Q115557395,rathaus,2026-04-16 14:32:35
1,132846993,node,Stadtverwaltung Korntal-Münchingen,Baden-Wuerttemberg,NaN,https://www.korntal-muenchingen.de,NaN,NaN,NaN,rathaus,2026-04-16 14:32:35
2,137982924,node,Rathaus,Baden-Wuerttemberg,"https://www.heidelberg.de/hd,Lde/HD/Rathaus.html",NaN,NaN,de:Rathaus (Heidelberg),Q660785,rathaus,2026-04-16 14:32:35
3,247470380,node,Rathaus Weilheim,Baden-Wuerttemberg,NaN,NaN,NaN,NaN,Q138764098,rathaus,2026-04-16 14:32:35
4,250211735,node,Rathaus,Baden-Wuerttemberg,https://www.korb.de/de/politik-verwaltung/rathaus,NaN,NaN,NaN,NaN,rathaus,2026-04-16 14:32:35
...,...,...,...,...,...,...,...,...,...,...,...
3735,259559998,way,Amtsgericht,Thueringen,NaN,http://www.thueringen.de/th4/olg/gerichte_in_t...,NaN,NaN,NaN,gericht,2026-04-16 14:58:04
3736,463494296,way,Amtsgericht Hildburghausen,Thueringen,https://gerichte.thueringen.de/gerichte-in-thu...,NaN,NaN,NaN,NaN,gericht,2026-04-16 14:58:04
3737,463494297,way,Amtsgericht Hildburghausen,Thueringen,https://gerichte.thueringen.de/gerichte-in-thu...,NaN,NaN,NaN,NaN,gericht,2026-04-16 14:58:04
3738,622818178,way,Landgericht Mühlhausen,Thueringen,NaN,NaN,NaN,NaN,Q1523562,gericht,2026-04-16 14:58:04
3739,10019540,relation,Bundesarbeitsgericht,Thueringen,NaN,NaN,NaN,NaN,Q176936,gericht,2026-04-16 14:58:04

In [2]:
cleaned_df = df[(df["website"].notna())][["name", "website", "federal_state", "profil"]]
cleaned_df

,name,website,federal_state,profil
2,Rathaus,"https://www.heidelberg.de/hd,Lde/HD/Rathaus.html",Baden-Wuerttemberg,rathaus
4,Rathaus,https://www.korb.de/de/politik-verwaltung/rathaus,Baden-Wuerttemberg,rathaus
5,Rathaus Staig,http://www.staig.de,Baden-Wuerttemberg,rathaus
7,Ortsverwaltung Haueneberstein,https://www.baden-baden.de/de/buergerservice/c...,Baden-Wuerttemberg,rathaus
8,Rathaus Wannweil,https://wannweil.de/,Baden-Wuerttemberg,rathaus
...,...,...,...,...
3730,Landgericht Erfurt,https://www.thueringen.de/th4/olg/gerichte_in_...,Thueringen,gericht
3731,Amtsgericht Sondershausen,https://www.thueringen.de/de/olg/gerichte_in_t...,Thueringen,gericht
3733,Amtsgericht Rudolstadt,https://www.thueringen.de/th4/olg/gerichte_in_...,Thueringen,gericht
3736,Amtsgericht Hildburghausen,https://gerichte.thueringen.de/gerichte-in-thu...,Thueringen,gericht
3737,Amtsgericht Hildburghausen,https://gerichte.thueringen.de/gerichte-in-thu...,Thueringen,gericht

In [3]:
import tldextract

def extract_root_domain(url):
    ext = tldextract.extract(url)
    return f"{ext.domain}.{ext.suffix}"

cleaned_df["root_domain"] = cleaned_df["website"].apply(extract_root_domain)
cleaned_df

,name,website,federal_state,profil,root_domain
2,Rathaus,"https://www.heidelberg.de/hd,Lde/HD/Rathaus.html",Baden-Wuerttemberg,rathaus,heidelberg.de
4,Rathaus,https://www.korb.de/de/politik-verwaltung/rathaus,Baden-Wuerttemberg,rathaus,korb.de
5,Rathaus Staig,http://www.staig.de,Baden-Wuerttemberg,rathaus,staig.de
7,Ortsverwaltung Haueneberstein,https://www.baden-baden.de/de/buergerservice/c...,Baden-Wuerttemberg,rathaus,baden-baden.de
8,Rathaus Wannweil,https://wannweil.de/,Baden-Wuerttemberg,rathaus,wannweil.de
...,...,...,...,...,...
3730,Landgericht Erfurt,https://www.thueringen.de/th4/olg/gerichte_in_...,Thueringen,gericht,thueringen.de
3731,Amtsgericht Sondershausen,https://www.thueringen.de/de/olg/gerichte_in_t...,Thueringen,gericht,thueringen.de
3733,Amtsgericht Rudolstadt,https://www.thueringen.de/th4/olg/gerichte_in_...,Thueringen,gericht,thueringen.de
3736,Amtsgericht Hildburghausen,https://gerichte.thueringen.de/gerichte-in-thu...,Thueringen,gericht,thueringen.de
3737,Amtsgericht Hildburghausen,https://gerichte.thueringen.de/gerichte-in-thu...,Thueringen,gericht,thueringen.de

In [ ]:
sample =  cleaned_df.sample(n=10)

for index, row in sample.iterrows():

In [20]:
import pandas as pd
import ast

df = pd.read_csv("D:\Projekte\S.M.A.R.T.-Sovereign_Mail_Assessment_and_Rating_Tool\scanner\enriched_domains.csv")


df["asn"] = df["asn"].apply(ast.literal_eval)

result = []

for _, row in df.iterrows():
    try:
        x = row["asn"]

        if not isinstance(x, list):
            continue

        orgs = {
            i["asn_org"]
            for i in x
            if isinstance(i, dict) and "asn_org" in i
        }

        result.append(list(orgs))

    except Exception:
        # komplett kaputte Zeile skippen
        continue

df["asn_org_unique"] = result

df

<>:4: SyntaxWarning: invalid escape sequence '\P'
<>:4: SyntaxWarning: invalid escape sequence '\P'
C:\Users\jujud\AppData\Local\Temp\ipykernel_17496\2331130100.py:4: SyntaxWarning: invalid escape sequence '\P'
  df = pd.read_csv("D:\Projekte\S.M.A.R.T.-Sovereign_Mail_Assessment_and_Rating_Tool\scanner\enriched_domains.csv")

,name,website,root_domain,federal_state,profil,domain,mx_records,ips,asn,smtp_banner,asn_org_unique
0,Rathaus,"https://www.heidelberg.de/hd,Lde/HD/Rathaus.html",heidelberg.de,Baden-Wuerttemberg,rathaus,heidelberg.de,"['mx7.kvnbw.de', 'mx8.kvnbw.de', 'mx9.kvnbw.de...","['194.0.94.48', '194.59.36.34', '194.59.36.35'...","[{'asn': '50964', 'asn_org': 'KOMM-ONE-AS, DE'...","['220 mx7.kvnbw.de ESMTP Postfix\r\n', '220 mx...","[KOMM-ONE-AS, DE]"
1,Rathaus,https://www.korb.de/de/politik-verwaltung/rathaus,korb.de,Baden-Wuerttemberg,rathaus,korb.de,"['mx9.kvnbw.de', 'mx7.kvnbw.de', 'mx8.kvnbw.de...","['194.0.94.48', '194.59.36.34', '194.59.36.35'...","[{'asn': '50964', 'asn_org': 'KOMM-ONE-AS, DE'...","['220 mx9.kvnbw.de ESMTP Postfix\r\n', '220 mx...","[KOMM-ONE-AS, DE]"
2,Rathaus Staig,http://www.staig.de,staig.de,Baden-Wuerttemberg,rathaus,staig.de,"['mx9.kvnbw.de', 'mx6.kvnbw.de', 'mx8.kvnbw.de...","['194.0.94.48', '194.59.36.34', '194.59.36.35'...","[{'asn': '50964', 'asn_org': 'KOMM-ONE-AS, DE'...","['220 mx9.kvnbw.de ESMTP Postfix\r\n', '220 mx...","[KOMM-ONE-AS, DE]"
3,Ortsverwaltung Haueneberstein,https://www.baden-baden.de/de/buergerservice/c...,baden-baden.de,Baden-Wuerttemberg,rathaus,baden-baden.de,"['mx6.kvnbw.de', 'mx9.kvnbw.de', 'mx7.kvnbw.de...","['194.0.94.48', '194.59.36.34', '194.59.36.35'...","[{'asn': '50964', 'asn_org': 'KOMM-ONE-AS, DE'...","['220 mx6.kvnbw.de ESMTP Postfix\r\n', '220 mx...","[KOMM-ONE-AS, DE]"
4,Rathaus Wannweil,https://wannweil.de/,wannweil.de,Baden-Wuerttemberg,rathaus,wannweil.de,"['mx00.ionos.de', 'mx01.ionos.de']","['217.72.192.67', '212.227.15.41']","[{'asn': '8560', 'asn_org': 'IONOS-AS This is ...",['554-kundenserver.de (mxeue002) Nemesis ESMTP...,"[IONOS-AS This is the joint network for IONOS,..."
...,...,...,...,...,...,...,...,...,...,...,...
2154,Landgericht Erfurt,https://www.thueringen.de/th4/olg/gerichte_in_...,thueringen.de,Thueringen,gericht,thueringen.de,['thmail01.thueringen.de'],['195.191.15.232'],"[{'asn': '196870', 'asn_org': 'FSTH-ASN, DE', ...","['220 thmail04.thueringen.de ESMTP Mon, 20 Apr...","[FSTH-ASN, DE]"
2155,Amtsgericht Sondershausen,https://www.thueringen.de/de/olg/gerichte_in_t...,thueringen.de,Thueringen,gericht,thueringen.de,['thmail01.thueringen.de'],['195.191.15.232'],"[{'asn': '196870', 'asn_org': 'FSTH-ASN, DE', ...","['220 thmail04.thueringen.de ESMTP Mon, 20 Apr...","[FSTH-ASN, DE]"
2156,Amtsgericht Rudolstadt,https://www.thueringen.de/th4/olg/gerichte_in_...,thueringen.de,Thueringen,gericht,thueringen.de,['thmail01.thueringen.de'],['195.191.15.232'],"[{'asn': '196870', 'asn_org': 'FSTH-ASN, DE', ...","['220 thmail04.thueringen.de ESMTP Mon, 20 Apr...","[FSTH-ASN, DE]"
2157,Amtsgericht Hildburghausen,https://gerichte.thueringen.de/gerichte-in-thu...,thueringen.de,Thueringen,gericht,thueringen.de,['thmail01.thueringen.de'],['195.191.15.232'],"[{'asn': '196870', 'asn_org': 'FSTH-ASN, DE', ...","['220 thmail04.thueringen.de ESMTP Mon, 20 Apr...","[FSTH-ASN, DE]"
2158,Amtsgericht Hildburghausen,https://gerichte.thueringen.de/gerichte-in-thu...,thueringen.de,Thueringen,gericht,thueringen.de,['thmail01.thueringen.de'],['195.191.15.232'],"[{'asn': '196870', 'asn_org': 'FSTH-ASN, DE', ...","['220 thmail04.thueringen.de ESMTP Mon, 20 Apr...","[FSTH-ASN, DE]"

In [ ]:
output_data = {
    "org":
}

In [1]:
import json

with open(r"C:\Projekte\S.M.A.R.T.-Sovereign_Mail_Assessment_and_Rating_Tool\scanner\cache_dump.json", 'r') as file:
    data = json.load(file)

print(json.dumps(data, indent=4))

{
    "mx:abfrage.bundeswirtschaftsministerium.de": [
        "mail.survey-it.dk",
        "mail2.survey-it.dk"
    ],
    "mx:ads.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:adele-esf.de": [
        "mail1.domainssaubillig.de"
    ],
    "mx:agrowetter.de": [
        "ofcsgdbm.dwd.de",
        "zbcsgdbm.dwd.de"
    ],
    "mx:agrowetter.eu": [
        "ofcsgdbm.dwd.de",
        "zbcsgdbm.dwd.de"
    ],
    "mx:agrarstatistik.bund.de": [
        ""
    ],
    "mx:aktionsplan-allergien.de": [
        ""
    ],
    "mx:allergien.bund.de": [
        ""
    ],
    "mx:alpenflugwetter.com": [
        "ofcsgdbm.dwd.de",
        "zbcsgdbm.dwd.de"
    ],
    "mx:alpenflugwetter.de": [
        "ofcsgdbm.dwd.de",
        "zbcsgdbm.dwd.de"
    ],
    "mx:alpenflugwetter.eu": [
        "zbcsgdbm.dwd.de",
        "ofcsgdbm.dwd.de"
    ],
    "mx:allergieportal.bund.de": [
        ""
    ],
    "mx:altersvorsorge-macht-schule.de": [
        "mail030.webhosting.manitu.net"
    ],
    "mx:altersvorsorgemachtschule.de": [
        "mail1.domainssaubillig.de"
    ],
    "mx:alpenwetter.eu": [
        "zbcsgdbm.dwd.de",
        "ofcsgdbm.dwd.de"
    ],
    "mx:alumni.bmas.de": [
        "bouncer.crsend.com"
    ],
    "mx:anmeldung.bundesfinanzministerium.de": [
        "letter.eyepin.com"
    ],
    "mx:api.mwscan.bund.de": [
        ""
    ],
    "mx:apptesting.bsi.bund.de": [
        ""
    ],
    "mx:apps2.bvl.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:arbeitderzukunft.de": [
        "localhost"
    ],
    "mx:arb-5.de": [
        "mail1.domainssaubillig.de"
    ],
    "mx:arbeitsagentur.de": [
        "mail2.arbeitsagentur.de",
        "mail1.arbeitsagentur.de"
    ],
    "mx:arbeitenbis67.de": [
        "mail1.domainssaubillig.de"
    ],
    "mx:arbeitsschutz-forschung.de": [
        "w01fbbf9.kasserver.com"
    ],
    "mx:armuts-und-reichtumsbericht.de": [
        "mx01.pixelpark.com"
    ],
    "mx:arbeitsministerium.eu": [
        "bmas.eu"
    ],
    "mx:arl-net.de": [
        "mail.arl-net.de"
    ],
    "mx:atlasta2030.bmi.bund.de": [
        ""
    ],
    "mx:auslandschulwesen.de": [
        "mail.auslandschulwesen.de"
    ],
    "mx:auslandsschulwesen.de": [
        "w01fa72b.kasserver.com",
        "w01fa72b.kasserver.com",
        "w01fa72b.kasserver.com"
    ],
    "mx:auslandsschulwesen.net": [
        "auslandsschulwesen-net.mail.eo.outlook.com"
    ],
    "mx:auswanderungswesen.de": [
        ""
    ],
    "mx:auswaertiges-amt.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:auslandsschulportal.de": [
        ""
    ],
    "mx:auslandsschulwesen.eu": [
        ""
    ],
    "mx:av.mwscan.bund.de": [
        ""
    ],
    "mx:baainbw.de": [
        ""
    ],
    "mx:badv.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:baf.bund.de": [
        "zbcsgbbm.gbbmvi-wan.de",
        "ofcsgbbm.gbbmvi-wan.de"
    ],
    "mx:bafg.de": [
        "ofcsgbbm.gbbmvi-wan.de",
        "zbcsgbbm.gbbmvi-wan.de"
    ],
    "mx:bafa.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bafoeg.online": [
        ""
    ],
    "mx:bafoeg-rueckzahlung.de": [
        ""
    ],
    "mx:bafa.de": [
        "mail2.babiel.net"
    ],
    "mx:bag.bund.de": [
        "zbcsgbbm.gbbmvi-wan.de",
        "ofcsgbbm.gbbmvi-wan.de"
    ],
    "mx:ballonwetter.de": [
        "zbcsgdbm.dwd.de",
        "ofcsgdbm.dwd.de"
    ],
    "mx:ballonwetter.eu": [
        "ofcsgdbm.dwd.de",
        "zbcsgdbm.dwd.de"
    ],
    "mx:bafin.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bakoev.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bafza.de": [
        "mxlb.ispgateway.de"
    ],
    "mx:bam.de": [
        "a1381.mx.srv.dfn.de",
        "c1381.mx.srv.dfn.de",
        "b1381.mx.srv.dfn.de"
    ],
    "mx:balm.bund.de": [
        "zbcsgbbm.gbbmvi-wan.de",
        "ofcsgbbm.gbbmvi-wan.de"
    ],
    "mx:bamf.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:banst-pt.de": [
        "mx2.mas.t-systems-service.com",
        "mx3.mas.t-systems-service.com",
        "mx1.mas.t-systems-service.com"
    ],
    "mx:ba-reform.de": [
        "mail1.domainssaubillig.de"
    ],
    "mx:bast.de": [
        "ofcsgbbm.gbbmvi-wan.de",
        "zbcsgbbm.gbbmvi-wan.de"
    ],
    "mx:barch.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:base.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:baua.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bas.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bav.bund.de": [
        "ofcsgbbm.gbbmvi-wan.de",
        "zbcsgbbm.gbbmvi-wan.de"
    ],
    "mx:baw.de": [
        "zbcsgbbm.gbbmvi-wan.de",
        "ofcsgbbm.gbbmvi-wan.de"
    ],
    "mx:baua.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bdbos.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bbk.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bbr.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bescha.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:beteiligung.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bev.bund.de": [
        "ofcsgbbm.gbbmvi-wan.de",
        "zbcsgbbm.gbbmvi-wan.de"
    ],
    "mx:bfarm.de": [
        "mx-d1.bfarm.de",
        "mx-d2.bfarm.de"
    ],
    "mx:bfe.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bfu-web.de": [
        "zbcsgbbm.gbbmvi-wan.de",
        "ofcsgbbm.gbbmvi-wan.de"
    ],
    "mx:bfs.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bfdi.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bfj.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bfn.de": [
        "mail2.bfn.de",
        "mail.bfn.de"
    ],
    "mx:bfs.de": [
        "mxdmz01-muc.bfs.de",
        "mx2.bund.de",
        "mx1.bund.de",
        "mxdmz01-sz.bfs.de"
    ],
    "mx:bfr.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bib.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bgh.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bildungskredit.online": [
        ""
    ],
    "mx:bibb.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bgr.bund.de": [
        ""
    ],
    "mx:bildungskredit.de": [
        "mail.bildungskredit.de"
    ],
    "mx:bildungspaket-bmas.de": [
        "mail1.domainssaubillig.de"
    ],
    "mx:bisp.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bitv-lotse.de": [
        "mail.cms-carrier.de"
    ],
    "mx:bkge.de": [
        "spamgw1.exedra.de",
        "spamgw2.exedra.de"
    ],
    "mx:bka.de": [
        "mail.publicsec.t-systems.net"
    ],
    "mx:bitvlotse.de": [
        "mail1.domainssaubillig.de"
    ],
    "mx:bkg.bund.de": [
        "gate2-f.bkg.bund.de"
    ],
    "mx:bmas.de": [
        "mx02.pixelpark.com",
        "mx01.pixelpark.com"
    ],
    "mx:ble.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:ble.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bmas.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bltu.bvl.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bmbf.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bmbf.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bmds.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bmdv.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bmel.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bmbfsfj.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bmftr.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bmg.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bmf.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bmel.de": [
        ""
    ],
    "mx:bmfsfj.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bmi.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bmleh.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bmj.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bmuv.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bmu.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bmjv.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bmukn.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bmv.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bmv-forschungsnetzwerk.bund.de": [
        "zbcsgbbm.gbbmvi-wan.de",
        "ofcsgbbm.gbbmvi-wan.de"
    ],
    "mx:bmvi.de": [
        "ofcsgbbm.gbbmvi-wan.de",
        "zbcsgbbm.gbbmvi-wan.de"
    ],
    "mx:bmvbs.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bmvg.de": [
        ""
    ],
    "mx:bmwi.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bmwi.de": [
        "smtp-fallback.corpex-net.de",
        "smtp-relay.corpex-net.de",
        "iris.corpex-net.de"
    ],
    "mx:bmz.de": [
        "mail2.babiel.net"
    ],
    "mx:bmwsb.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bnd.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bmwk.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:breitband-atlas.de": [
        "rzs02.init.de",
        "rzs01.init.de"
    ],
    "mx:bpra.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bsg.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:briefing4pilot.de": [
        "mail1.domainssaubillig.de"
    ],
    "mx:bsu-bund.de": [
        "zbcsgbbm.gbbmvi-wan.de",
        "ofcsgbbm.gbbmvi-wan.de"
    ],
    "mx:bstu.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bsi.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:buehnenversorgung.de": [
        "mx2.versorgungskammer.de",
        "mx1.versorgungskammer.de"
    ],
    "mx:buel.bmel.de": [
        ""
    ],
    "mx:bund.online": [
        ""
    ],
    "mx:bund.services": [
        ""
    ],
    "mx:bundesarbeitsgericht.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bundesamtsozialesicherung.de": [
        "mail.bundesamtsozialesicherung.de"
    ],
    "mx:bundesarchiv.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bundescriminalamt.de": [
        "mail1.domainssaubillig.de"
    ],
    "mx:bundesjustizamt.de": [
        "mail.bundesjustizamt.de"
    ],
    "mx:bundeskriminalamt.net": [
        "smtp.ts-businessmail.de"
    ],
    "mx:bundeskriminalamt.org": [
        "smtp.ts-businessmail.de"
    ],
    "mx:bundeshaus.de": [
        "parking12.kv.de"
    ],
    "mx:bundeskartellamt.de": [
        "smtpin.rzone.de"
    ],
    "mx:bundesimmobilien.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bundesnetzagentur.de": [
        "vmail1.bnetza.de",
        "vmail2.bnetza.de"
    ],
    "mx:bundeskriminalamt.de": [
        "smtp.ts-businessmail.de"
    ],
    "mx:bundeskanzleramt.de": [
        "bundeskanzleramt.de"
    ],
    "mx:bundespruefstelle.de": [
        "rzs01.init.de",
        "rzs02.init.de"
    ],
    "mx:bundesregierung.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bundessortenamt.de": [
        "mforward.dtag.de",
        "email.bundessortenamt.de",
        "mail.bundessortenamt.de"
    ],
    "mx:bundesrechnungshof.de": [
        "bundesrechnungshof-de.mail.protection.outlook.com"
    ],
    "mx:bundesrat.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bundespolizei.de": [
        "mail.bundespolizei.de"
    ],
    "mx:bundestag.de": [
        "mail4.dbtg.de",
        "mail3.dbtg.de",
        "mail1.dbtg.de",
        "mail2.dbtg.de"
    ],
    "mx:bundesstelle-fuer-informationstechnik.de": [
        "arend.uberspace.de"
    ],
    "mx:bundespraesident.de": [
        "mail.bundespraesident.de"
    ],
    "mx:bundestag.eu": [
        ""
    ],
    "mx:bundestag-magazin.de": [
        "mail1.domainssaubillig.de"
    ],
    "mx:bundestag-und-schule.de": [
        "mail1.domainssaubillig.de"
    ],
    "mx:bundesverfassungsgericht.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bundessprachenamt.de": [
        "mx01.ionos.de",
        "mx00.ionos.de"
    ],
    "mx:bundestag-online.de": [
        "mail1.domainssaubillig.de"
    ],
    "mx:bundessozialministerium.eu": [
        "bmas.eu"
    ],
    "mx:bundestagspraesidentin.de": [
        ""
    ],
    "mx:bundestagspraesident.de": [
        ""
    ],
    "mx:bundestagsarena.de": [
        "mail.bundestagsarena.de"
    ],
    "mx:bva.services": [
        ""
    ],
    "mx:bundesverwaltungsamt.de": [
        "mail.bundesverwaltungsamt.de"
    ],
    "mx:bundesversammlung.de": [
        ""
    ],
    "mx:bva.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bva.website": [
        ""
    ],
    "mx:bundeswahlleiter.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bva-bund.de": [
        ""
    ],
    "mx:bva-dienstleistungszentrum.de": [
        ""
    ],
    "mx:bvl.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bzkj.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:bzst.bund.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:bzga.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:cert-bund.de": [
        "mx.cert-bund.de"
    ],
    "mx:cdn.mwscan.bund.de": [
        ""
    ],
    "mx:climatemonitoring.eu": [
        "zbcsgdbm.dwd.de",
        "ofcsgdbm.dwd.de"
    ],
    "mx:climateservice.eu": [
        "zbcsgbbm.gbbmvi-wan.de",
        "ofcsgbbm.gbbmvi-wan.de"
    ],
    "mx:climateservices.eu": [
        "zbcsgbbm.gbbmvi-wan.de",
        "ofcsgbbm.gbbmvi-wan.de"
    ],
    "mx:climateservices.de": [
        "ofcsgbbm.gbbmvi-wan.de",
        "zbcsgbbm.gbbmvi-wan.de"
    ],
    "mx:cmsaf.eu": [
        "zbcsgbbm.gbbmvi-wan.de",
        "ofcsgbbm.gbbmvi-wan.de"
    ],
    "mx:climatemonitoring.de": [
        "ofcsgdbm.dwd.de",
        "zbcsgdbm.dwd.de"
    ],
    "mx:csr-in-deutschland.de": [
        "mx01.pixelpark.com",
        "mx02.pixelpark.com"
    ],
    "mx:cr.bmas.de": [
        "bouncer.crsend.com"
    ],
    "mx:csr-preis-bund.de": [
        "mx01.pixelpark.com",
        "mx02.pixelpark.com"
    ],
    "mx:d115.bvl.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:dainst.org": [
        "mail.dainst.org"
    ],
    "mx:das-halbe-leben.de": [
        "www26.your-server.de"
    ],
    "mx:das-halbe-leben.com": [
        "www26.your-server.de"
    ],
    "mx:dashalbeleben.de": [
        "www26.your-server.de"
    ],
    "mx:das-parlament.de": [
        "mail2.babiel.net"
    ],
    "mx:datenhandbuch-bundestag.de": [
        ""
    ],
    "mx:dbtg.eu": [
        ""
    ],
    "mx:dbt-internet.de": [
        "mail1.babiel.com"
    ],
    "mx:dbtg.tv": [
        ""
    ],
    "mx:dbtg-newsletter.de": [
        "mail1.babiel.com"
    ],
    "mx:deine-digitale-seite.bsi.bund.de": [
        ""
    ],
    "mx:dehst.de": [
        "ubamail.tcc-products.de"
    ],
    "mx:der-mindestlohn-kommt.de": [
        "mx2.hostinger.com",
        "mx1.hostinger.com"
    ],
    "mx:derbevoelkerung.de": [
        "mx00.ionos.de",
        "mx01.ionos.de"
    ],
    "mx:dekabank.de": [
        "primary.emea.email.fireeyecloud.com",
        "alt3.emea.email.fireeyecloud.com",
        "mx.emea.email.fireeyecloud.com",
        "mailin.deka.de",
        "alt2.emea.email.fireeyecloud.com",
        "alt1.emea.email.fireeyecloud.com"
    ],
    "mx:deutscher-bundestag.eu": [
        ""
    ],
    "mx:destatis.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:deutscherklimaatlas.de": [
        "zbcsgdbm.dwd.de",
        "ofcsgdbm.dwd.de"
    ],
    "mx:deutscher-bundestag.de": [
        ""
    ],
    "mx:deutscher-klimaatlas.de": [
        "ofcsgdbm.dwd.de",
        "zbcsgdbm.dwd.de"
    ],
    "mx:deutscherwetterdienst.com": [
        "zbcsgdbm.dwd.de",
        "ofcsgdbm.dwd.de"
    ],
    "mx:deutscherdom.de": [
        ""
    ],
    "mx:deutscher-wetterdienst.de": [
        "zbcsgdbm.dwd.de",
        "ofcsgdbm.dwd.de"
    ],
    "mx:deutscher-wetterdienst.com": [
        "ofcsgdbm.dwd.de",
        "zbcsgdbm.dwd.de"
    ],
    "mx:deutscherwetterdienst.de": [
        "ofcsgdbm.dwd.de",
        "zbcsgdbm.dwd.de"
    ],
    "mx:deutscherwetterdienst.eu": [
        "zbcsgdbm.dwd.de",
        "ofcsgdbm.dwd.de"
    ],
    "mx:deutschesklimaportal.de": [
        "ofcsgdbm.dwd.de"
    ],
    "mx:deutsches-klimaportal.de": [
        "ofcsgdbm.dwd.de",
        "zbcsgdbm.dwd.de"
    ],
    "mx:deutscher-wetterdienst.eu": [
        "route3.mx.cloudflare.net",
        "route2.mx.cloudflare.net",
        "route1.mx.cloudflare.net"
    ],
    "mx:deutsches-parlament.eu": [
        ""
    ],
    "mx:deutscheweine.de": [
        "deutscheweine-de.mail.protection.outlook.com"
    ],
    "mx:deutschesheer.de": [
        ""
    ],
    "mx:deutsches-museum.de": [
        "smtp.google.com"
    ],
    "mx:dienstreisezentrum.de": [
        ""
    ],
    "mx:dienstleistungszentrum.de": [
        ""
    ],
    "mx:digitalservice.bund.de": [
        "ALT3.ASPMX.L.GOOGLE.COM",
        "ALT4.ASPMX.L.GOOGLE.COM",
        "ALT1.ASPMX.L.GOOGLE.COM",
        "ASPMX.L.GOOGLE.COM",
        "ALT2.ASPMX.L.GOOGLE.COM"
    ],
    "mx:dip21.de": [
        ""
    ],
    "mx:dklip.de": [
        "ofcsgdbm.dwd.de"
    ],
    "mx:d-klip.de": [
        "ofcsgdbm.dwd.de"
    ],
    "mx:dimdi.de": [
        "mx-d2.bfarm.de",
        "mx-d1.bfarm.de"
    ],
    "mx:dip-online.de": [
        "w01f4a25.kasserver.com"
    ],
    "mx:doi-de.net": [
        "mail.doi-de.net"
    ],
    "mx:doi-sec-de.net": [
        ""
    ],
    "mx:dnb.de": [
        "mail.dnb.de"
    ],
    "mx:dorfwettbewerb.bund.de": [
        ""
    ],
    "mx:dsd-weltweit.de": [
        "mail.dsd-weltweit.de"
    ],
    "mx:dpma.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:dwd.bund.de": [
        "zbcsgbbm.gbbmvi-wan.de",
        "ofcsgbbm.gbbmvi-wan.de"
    ],
    "mx:dwd.de": [
        "zbcsgdop.dwd.de",
        "zbcsgdbm.dwd.de",
        "ofcsgdop.dwd.de",
        "ofcsgdbm.dwd.de"
    ],
    "mx:dsc.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:dsd.online": [
        ""
    ],
    "mx:dwd.eu": [
        "ofcsgdbm.dwd.de",
        "zbcsgdbm.dwd.de"
    ],
    "mx:dwd-shop.eu": [
        "ofcsgdbm.dwd.de",
        "zbcsgdbm.dwd.de"
    ],
    "mx:dzsf.bund.de": [
        "ofcsgbbm.gbbmvi-wan.de",
        "zbcsgbbm.gbbmvi-wan.de"
    ],
    "mx:eba.bund.de": [
        "zbcsgbbm.gbbmvi-wan.de",
        "ofcsgbbm.gbbmvi-wan.de"
    ],
    "mx:dwd-shop.de": [
        "ofcsgdbm.dwd.de",
        "zbcsgdbm.dwd.de"
    ],
    "mx:bpb.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:ecert.bvl.bund.de": [
        "mx2.bund.de",
        "mx1.bund.de"
    ],
    "mx:eisenbahn-unfalluntersuchung.de": [
        "zbcsgbbm.gbbmvi-wan.de",
        "ofcsgbbm.gbbmvi-wan.de"
    ],
    "mx:einfach-teilhaben.de": [
        "mx1.bund.de",
        "mx2.bund.de"
    ],
    "mx:ein-und-ausblicke.de": [
        "w01aee26.kasserver.com"
    ],
    "mx:eparlament.de": [
        "mx01.ionos.de",
        "mx00.ionos.de"
    ],
    "mx:esf.de": [
        "mx01.pixelpark.com",
        "mx02.pixelpark.com"
    ],
    "mx:euginius.bvl.bund.de": [

In [7]:
mx_domains = []
for key,value in data.items():
    mx_domains = mx_domains + value
mx_domains

['mail.survey-it.dk',
 'mail2.survey-it.dk',
 'mx2.bund.de',
 'mx1.bund.de',
 'mail1.domainssaubillig.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 '',
 '',
 '',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 '',
 'mail030.webhosting.manitu.net',
 'mail1.domainssaubillig.de',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'bouncer.crsend.com',
 'letter.eyepin.com',
 '',
 '',
 'mx1.bund.de',
 'mx2.bund.de',
 'localhost',
 'mail1.domainssaubillig.de',
 'mail2.arbeitsagentur.de',
 'mail1.arbeitsagentur.de',
 'mail1.domainssaubillig.de',
 'w01fbbf9.kasserver.com',
 'mx01.pixelpark.com',
 'bmas.eu',
 'mail.arl-net.de',
 '',
 'mail.auslandschulwesen.de',
 'w01fa72b.kasserver.com',
 'w01fa72b.kasserver.com',
 'w01fa72b.kasserver.com',
 'auslandsschulwesen-net.mail.eo.outlook.com',
 '',
 'mx2.bund.de',
 'mx1.bund.de',
 '',
 '',
 '',
 '',
 'mx2.bund.de',
 'mx1.bund.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'mx2.bund.de',
 'mx1.bund.de',
 '',
 '',
 'mail2.babiel.net',
 'zbcsgbbm.gbbmvi-wan.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mxlb.ispgateway.de',
 'a1381.mx.srv.dfn.de',
 'c1381.mx.srv.dfn.de',
 'b1381.mx.srv.dfn.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx2.mas.t-systems-service.com',
 'mx3.mas.t-systems-service.com',
 'mx1.mas.t-systems-service.com',
 'mail1.domainssaubillig.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'mx-d1.bfarm.de',
 'mx-d2.bfarm.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mail2.bfn.de',
 'mail.bfn.de',
 'mxdmz01-muc.bfs.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mxdmz01-sz.bfs.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 '',
 'mx1.bund.de',
 'mx2.bund.de',
 '',
 'mail.bildungskredit.de',
 'mail1.domainssaubillig.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mail.cms-carrier.de',
 'spamgw1.exedra.de',
 'spamgw2.exedra.de',
 'mail.publicsec.t-systems.net',
 'mail1.domainssaubillig.de',
 'gate2-f.bkg.bund.de',
 'mx02.pixelpark.com',
 'mx01.pixelpark.com',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 '',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'mx1.bund.de',
 'mx2.bund.de',
 '',
 'mx1.bund.de',
 'mx2.bund.de',
 'smtp-fallback.corpex-net.de',
 'smtp-relay.corpex-net.de',
 'iris.corpex-net.de',
 'mail2.babiel.net',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'rzs02.init.de',
 'rzs01.init.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mail1.domainssaubillig.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx2.versorgungskammer.de',
 'mx1.versorgungskammer.de',
 '',
 '',
 '',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mail.bundesamtsozialesicherung.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mail1.domainssaubillig.de',
 'mail.bundesjustizamt.de',
 'smtp.ts-businessmail.de',
 'smtp.ts-businessmail.de',
 'parking12.kv.de',
 'smtpin.rzone.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'vmail1.bnetza.de',
 'vmail2.bnetza.de',
 'smtp.ts-businessmail.de',
 'bundeskanzleramt.de',
 'rzs01.init.de',
 'rzs02.init.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mforward.dtag.de',
 'email.bundessortenamt.de',
 'mail.bundessortenamt.de',
 'bundesrechnungshof-de.mail.protection.outlook.com',
 'mx1.bund.de',
 'mx2.bund.de',
 'mail.bundespolizei.de',
 'mail4.dbtg.de',
 'mail3.dbtg.de',
 'mail1.dbtg.de',
 'mail2.dbtg.de',
 'arend.uberspace.de',
 'mail.bundespraesident.de',
 '',
 'mail1.domainssaubillig.de',
 'mail1.domainssaubillig.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx01.ionos.de',
 'mx00.ionos.de',
 'mail1.domainssaubillig.de',
 'bmas.eu',
 '',
 '',
 'mail.bundestagsarena.de',
 '',
 'mail.bundesverwaltungsamt.de',
 '',
 'mx1.bund.de',
 'mx2.bund.de',
 '',
 'mx1.bund.de',
 'mx2.bund.de',
 '',
 '',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx.cert-bund.de',
 '',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'mx01.pixelpark.com',
 'mx02.pixelpark.com',
 'bouncer.crsend.com',
 'mx01.pixelpark.com',
 'mx02.pixelpark.com',
 'mx2.bund.de',
 'mx1.bund.de',
 'mail.dainst.org',
 'www26.your-server.de',
 'www26.your-server.de',
 'www26.your-server.de',
 'mail2.babiel.net',
 '',
 '',
 'mail1.babiel.com',
 '',
 'mail1.babiel.com',
 '',
 'ubamail.tcc-products.de',
 'mx2.hostinger.com',
 'mx1.hostinger.com',
 'mx00.ionos.de',
 'mx01.ionos.de',
 'primary.emea.email.fireeyecloud.com',
 'alt3.emea.email.fireeyecloud.com',
 'mx.emea.email.fireeyecloud.com',
 'mailin.deka.de',
 'alt2.emea.email.fireeyecloud.com',
 'alt1.emea.email.fireeyecloud.com',
 '',
 'mx1.bund.de',
 'mx2.bund.de',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 '',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 '',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'route3.mx.cloudflare.net',
 'route2.mx.cloudflare.net',
 'route1.mx.cloudflare.net',
 '',
 'deutscheweine-de.mail.protection.outlook.com',
 '',
 'smtp.google.com',
 '',
 '',
 'ALT3.ASPMX.L.GOOGLE.COM',
 'ALT4.ASPMX.L.GOOGLE.COM',
 'ALT1.ASPMX.L.GOOGLE.COM',
 'ASPMX.L.GOOGLE.COM',
 'ALT2.ASPMX.L.GOOGLE.COM',
 '',
 'ofcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'mx-d2.bfarm.de',
 'mx-d1.bfarm.de',
 'w01f4a25.kasserver.com',
 'mail.doi-de.net',
 '',
 'mail.dnb.de',
 '',
 'mail.dsd-weltweit.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'zbcsgdop.dwd.de',
 'zbcsgdbm.dwd.de',
 'ofcsgdop.dwd.de',
 'ofcsgdbm.dwd.de',
 'mx2.bund.de',
 'mx1.bund.de',
 '',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'w01aee26.kasserver.com',
 'mx01.ionos.de',
 'mx00.ionos.de',
 'mx01.pixelpark.com',
 'mx02.pixelpark.com',
 'mx2.bund.de',
 'mx1.bund.de',
 '',
 '',
 'mail.favorit.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'mx01.pixelpark.com',
 'mx02.pixelpark.com',
 'mail.finanzforscher.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'bmail.deutsche-finanzagentur.de',
 'mail.deutsche-finanzagentur.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'mx2.bmbfcluster.de',
 'mx.bmbfcluster.de',
 'mailgate-1.zdv.net',
 'mailgate-2.zdv.net',
 'mailgate-3.zdv.net',
 'rzs01.init.de',
 'rzs02.init.de',
 'forum.bfdi.bund.de',
 '',
 'cluster4a.eu.messagelabs.com',
 'cluster4.eu.messagelabs.com',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'gate2-f.bkg.bund.de',
 'gate1-f.bkg.bund.de',
 'gate2-f.bkg.bund.de',
 'mx02.pixelpark.com',
 'mx01.pixelpark.com',
 'a2781.mx.srv.dfn.de',
 'b2781.mx.srv.dfn.de',
 'c2781.mx.srv.dfn.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'r2mr5.init.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'www135.your-server.de',
 'mx1.bund.de',
 'mx2.bund.de',
 '',
 'localhost',
 'parking10.kv.de',
 'mxe965.netcup.net',
 'mail.ida.de',
 'info.auswaertiges-amt.de',
 'b1233.mx.srv.dfn.de',
 'c1233.mx.srv.dfn.de',
 'a1233.mx.srv.dfn.de',
 'mx01.pixelpark.com',
 'mail1.domainssaubillig.de',
 'mx02.pixelpark.com',
 'mx01.pixelpark.com',
 'mail.integration-in-deutschland.de',
 'dedi1996.your-server.de',
 '',
 '',
 'r2mr5.init.de',
 'mx2.bund.de',
 'mx1.bund.de',
 '',
 'styx2.julius-kuehn.de',
 'styx1.julius-kuehn.de',
 'mail1.domainssaubillig.de',
 'mx0.cloud2.softgarden.de',
 'mx0.cloud1.softgarden.de',
 'mail.jobquick.net',
 '',
 'ofcsgbbm.gbbmvi-wan.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'mx156.hostedmxserver.com',
 '',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'mx10.kfw.de',
 'mx20.kfw.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mail.survey-it.dk',
 'mail2.survey-it.dk',
 'mail.survey-it.dk',
 'mail2.survey-it.dk',
 'kulturstaatsminister.de',
 '',
 '',
 'zbcsgbbm.gbbmvi-wan.de',
 'ofcsgbbm.gbbmvi-wan.de',
 '',
 'zbcsgbbm.gbbmvi-wan.de',
 'ofcsgbbm.gbbmvi-wan.de',
 '',
 '',
 '',
 'mail01.bgr.de',
 'mail02.bgr.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 '',
 '',
 'bouncer.crsend.com',
 'mx02.pixelpark.com',
 'mx01.pixelpark.com',
 '',
 '',
 '',
 '',
 '',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'localhost',
 'localhost',
 'mail.meinmikrokredit.de',
 'mx2.bund.de',
 'mx1.bund.de',
 '',
 'mail.meet.bdbos.bund.de',
 'halo278.lcube-server.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'zbcsgbbm.gbbmvi-wan.de',
 '',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx01.pixelpark.com',
 'newsletter.baks.bund.de',
 'bouncer.crsend.com',
 'rzs01.init.de',
 'rzs02.init.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'gate2-f.bkg.bund.de',
 'mail1.domainssaubillig.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx2.versorgungskammer.de',
 'mx1.versorgungskammer.de',
 'mail.orghandbuch.de',
 'monopolkommission.bund.de',
 '',
 '',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 '',
 '',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'mail.personalausweisportal.de',
 'sv-spam-01.pei.de',
 'sv-avw-02.pei.de',
 'mail.personenstandsrecht.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'secondary.netuse.de',
 'secondary2.sczn.de',
 'mail.sczn.de',
 'mail.polizei-info.de',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 '',
 'mx2.bund.de',
 'mx1.bund.de',
 '',
 'ofcsgbbm.gbbmvi-wan.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'bouncer.crsend.com',
 'mx1.berlin.ptb.de',
 'mx1.bs.ptb.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'mx1a.maxrubner.de',
 'mx2a.maxrubner.de',
 '',
 'mail.register-factory.de',
 'mx.eyepinnews.com',
 '',
 '',
 'report.ofcsgbbm.gbbmdv.bund.de',
 '',
 'letter.eyepin.com',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 '',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'mx01.pixelpark.com',
 'mx02.pixelpark.com',
 'mx01.ionos.de',
 'mx00.ionos.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx02.pixelpark.com',
 'mx01.pixelpark.com',
 'social.bund.de',
 'mx1.comspace.de',
 'mx2.comspace.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'bmas.eu',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 '',
 'mail.testa-de.net',
 'a1481.mx.srv.dfn.de',
 'b1481.mx.srv.dfn.de',
 'c1481.mx.srv.dfn.de',
 '',
 'mx2.bund.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'mail.tln-mobility.eu',
 'mx1.agenturserver.de',
 'mx4.agenturserver.de',
 'mx2.agenturserver.de',
 'mx3.agenturserver.de',
 'mail2.uba.de',
 'mail1.uba.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'mx2.comspace.de',
 'mx1.comspace.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'ofcsgbbm.gbbmvi-wan.de',
 'mx.vbl.de',
 'mail1.domainssaubillig.de',
 'arend.uberspace.de',
 'webmail.verfassungsschutz.de',
 '',
 'ofcsgbbm.gbbmvi-wan.de',
 'zbcsgbbm.gbbmvi-wan.de',
 'lxmxext1.bfinv.de',
 'lxmxext2.bfinv.de',
 '',
 'mx2.bund.de',
 'mx1.bund.de',
 'mail1.domainssaubillig.de',
 'localhost',
 'mail.ud10.udmedia.de',
 '',
 'mx1.bund.de',
 'mx2.bund.de',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'ofcsgdbm.dwd.de',
 'zbcsgdbm.dwd.de',
 'mail1.domainssaubillig.de',
 'mail.wie-wollen-wir-arbeiten.de',
 'mx2f68.netcup.net',
 'ofcsgbbm.gbbmvi-wan.de',
 'zbcsgbbm.gbbmvi-wan.de',
 '',
 '',
 'smtp.ts-businessmail.de',
 'smtp.ts-businessmail.de',
 'smtp.ts-businessmail.de',
 'mx2.bund.de',
 'mx1.bund.de',
 'secondary.netuse.de',
 'mail.sczn.de',
 'secondary2.sczn.de',
 'mail1.domainssaubillig.de',
 'mail1.domainssaubillig.de',
 'mxlb.ispgateway.de',
 'rzs01.init.de',
 'mail.zuwes.de',
 '',
 'smtpin.rzone.de',
 'mx1.bund.de',
 'mx2.bund.de',
 'mx1.comspace.de',
 'mx2.comspace.de']